### ISSUE TITLE
how to set access token?

### ISSUE THREAD

**Issue by eseedo** [Mostafa-Ehab/Twitter-Scrapper#2]
Thanks for your repo. 
And here is the question:
You mentioned 'Make sure to set your access token an index.py on line 119'
but index.py in vs code shows only 95 lines of code. also how to get the access token and set it if there is such a line of code?
Thanks a lot.
![Uploading 01.png…]()

**Comment by Mostafa-Ehab** [comment]
I have updated the read.me file please check it again.
