### ISSUE TITLE
possible banning of the tool? 

### ISSUE THREAD

**Issue by ainteligencia** [Mostafa-Ehab/Twitter-Scrapper#3]
Hi, how are you? I tell you that your code was working great until today. where I ran it with 20 accounts and each account was extracting 5 twitter. but suddenly I get the message Something went wrong. Try to reload. with the try again button and it doesn't let me pass. i know little about selenium, what do you recommend me to do to continue with the execution. thanks.

![Captura desde 2024-03-20 08-41-04](https://github.com/Mostafa-Ehab/Twitter-Scrapper/assets/108409397/60f699f4-0bd1-4bac-a1ef-e96000e1754a)

**Comment by Mostafa-Ehab** [comment]
Thanks for your comment!

There's a temporary ban happens from twitter's server when the rate of requests increase.
A proper solution is to increase the delay between the requests, I hope this helps you.

Again, thanks for letting me know about this issue.
